// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/[...]').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/user.get').default>>>>
    }
    '/api/projects/:projectId/definition': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/definition.post').default>>>>
    }
    '/api/projects/:projectId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/index').default>>>>
    }
    '/api/projects/:projectId/services/:serviceId': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/services/[serviceId]/index').default>>>>
    }
    '/api/projects/:projectId/services': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/[projectId]/services/index').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects/index').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_content/query/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/query': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/query').default>>>>
    }
    '/api/_content/cache.1709982541136.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/cache').default>>>>
    }
    '/api/_content/navigation/:qid/**:params': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation/:qid': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
    '/api/_content/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/content/dist/runtime/server/api/navigation').default>>>>
    }
  }
}
export {}